from pathlib import Path
import re

path = Path('/home/ubuntu/proline/client/src/pages/Home.tsx')
text = path.read_text()
replacement = r'''function SettingsPanel({ templateId, setTemplateId, themeId, setThemeId, onExport, onClose }: { templateId: ExcelTemplateId; setTemplateId: (id: ExcelTemplateId) => void; themeId: ThemeId; setThemeId: (id: ThemeId) => void; onExport: (format: "csv" | "xls") => void; onClose: () => void }) {
  const activeTheme = themePresets.find((theme) => theme.id === themeId) || themePresets[0];
  return <div className="fixed inset-0 z-[60] bg-[#02070B]/75 backdrop-blur-sm flex items-center justify-center p-3 sm:p-5" onMouseDown={(event) => event.target === event.currentTarget && onClose()}>
    <div className="w-full max-w-2xl max-h-[calc(100vh-2rem)] overflow-y-auto rounded-2xl border border-white/10 bg-[#0D1C29] shadow-2xl">
      <div className="flex items-start justify-between gap-4 border-b border-white/[.08] px-4 sm:px-6 py-4 sm:py-5"><div><div className="flex items-center gap-2 text-[10px] uppercase tracking-[.16em] font-bold" style={{ color: activeTheme.accent }}><Settings size={13} /> Sistem ayarları</div><h2 className="font-display text-xl sm:text-2xl font-bold mt-2">PROLINE Settings</h2><p className="text-xs leading-5 text-[#8292A0] mt-2 max-w-lg">Tema və Excel çıxış seçimlərini buradan idarə edin.</p></div><button onClick={onClose} className="p-2 rounded-lg text-[#81919E] hover:bg-white/10"><X size={18} /></button></div>
      <div className="p-4 sm:p-6 space-y-6">
        <section><div className="mb-3"><div className="text-[10px] uppercase tracking-[.14em] font-bold text-[#6E808D]">Rəngli tema</div><div className="text-xs text-[#8292A0] mt-1">Seçilən rəng palitrası panelin əsas vurğularında yadda saxlanılır.</div></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{themePresets.map((theme) => <button key={theme.id} onClick={() => setThemeId(theme.id)} className={`text-left rounded-xl border p-3.5 transition ${themeId === theme.id ? "border-white/40" : "border-white/[.09] hover:border-white/20"}`} style={{ background: `linear-gradient(135deg, ${theme.glow}, rgba(255,255,255,.025))` }}><div className="flex items-center gap-3"><span className="h-8 w-8 rounded-full border-2 border-white/20" style={{ background: `linear-gradient(135deg, ${theme.accent}, ${theme.accentHover})`, boxShadow: `0 0 18px ${theme.glow}` }} /><span className="min-w-0"><span className="block text-sm font-semibold text-[#E8EEF2]">{theme.name}</span><span className="block text-[10px] leading-4 text-[#8292A0] mt-0.5">{theme.description}</span></span>{themeId === theme.id && <Check size={16} className="ml-auto shrink-0" style={{ color: theme.accent }} />}</div></button>)}</div></section>
        <section><div className="mb-3"><div className="text-[10px] uppercase tracking-[.14em] font-bold text-[#6E808D]">Excel çıxış şablonu</div><div className="text-xs text-[#8292A0] mt-1">Import etdiyiniz zaman Excel-də məlumatlar seçilən şablonun sütunları ilə çıxacaq.</div></div><div className="space-y-3">{excelTemplates.map((template) => <button key={template.id} onClick={() => setTemplateId(template.id)} className={`w-full text-left rounded-xl border p-4 transition ${templateId === template.id ? "border-white/30" : "border-white/[.09] hover:border-white/20"}`} style={templateId === template.id ? { borderColor: activeTheme.accent, background: activeTheme.glow } : undefined}><div className="flex items-start gap-3"><span className="mt-0.5 h-5 w-5 rounded-full border flex items-center justify-center shrink-0" style={templateId === template.id ? { borderColor: activeTheme.accent, backgroundColor: activeTheme.accent, color: "#1B1713" } : { borderColor: "rgba(255,255,255,.2)" }}>{templateId === template.id && <Check size={13} />}</span><span className="min-w-0"><span className="block text-sm font-semibold text-[#E8EEF2]">{template.name}</span><span className="block text-xs leading-5 text-[#8292A0] mt-1">{template.description}</span><span className="block text-[10px] leading-4 text-[#A8B6C0] mt-2">Sütunlar: {template.fields.join(" · ")}</span></span></div></button>)}</div></section>
      </div>
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 border-t border-white/[.08] bg-[#0A1722] px-4 sm:px-6 py-4"><span className="text-[11px] text-[#718391]">Aktiv: <strong style={{ color: activeTheme.accent }}>{excelTemplates.find((template) => template.id === templateId)?.name}</strong></span><div className="flex flex-col sm:flex-row gap-2"><button onClick={() => onExport("csv")} className="inline-flex items-center justify-center gap-2 rounded-lg border border-white/10 px-3.5 py-2.5 text-xs font-bold text-[#C6D0D6] hover:bg-white/5"><Download size={14} /> CSV çıxart</button><button onClick={() => onExport("xls")} className="inline-flex items-center justify-center gap-2 rounded-lg px-3.5 py-2.5 text-xs font-bold text-[#1B1713]" style={{ backgroundColor: activeTheme.accent }}><Download size={14} /> Excel çıxart</button></div></div>
    </div>
  </div>;
}
'''
new_text, count = re.subn(r'function SettingsPanel\([\s\S]*$', replacement, text, count=1)
if count != 1:
    raise SystemExit(f'SettingsPanel replacement count={count}')
path.write_text(new_text)
