from pathlib import Path
p = Path('/home/ubuntu/proline/client/src/pages/Home.tsx')
s = p.read_text()
start = s.index('function OrderCard')
end = s.index('function OrderModal', start)
replacement = '''function durationLabel(iso: string, now: number) { const totalMinutes = Math.max(0, Math.floor((now - new Date(iso).getTime()) / 60000)); const days = Math.floor(totalMinutes / 1440); const hours = Math.floor((totalMinutes % 1440) / 60); const mins = totalMinutes % 60; return days ? `${days}g ${hours}s` : hours ? `${hours}s ${mins}d` : `${mins}d`; }
function OrderCard({ order, onClick, onDragStart, onDragEnd }: { order: Order; onClick: () => void; onDragStart: () => void; onDragEnd: () => void }) { const [p, color] = priorityMeta(order.priority); const [now, setNow] = useState(Date.now()); useEffect(() => { const id = window.setInterval(() => setNow(Date.now()), 60000); return () => window.clearInterval(id); }, []); const pending = order.pendingTo ? columns.find((c) => c.id === order.pendingTo) : null; return <article draggable={!order.pendingTo} onDragStart={onDragStart} onDragEnd={onDragEnd} onClick={onClick} className={`group rounded-lg border bg-[#122230] p-3.5 transition-all duration-200 cursor-pointer shadow-[0_4px_18px_rgba(0,0,0,.12)] ${pending ? "border-[#D7B45A]/45" : "border-white/[.08] hover:border-[#D78A4A]/50 hover:bg-[#162A39]"}`}><div className="flex items-start justify-between gap-2"><div className="flex items-center gap-2 min-w-0"><GripVertical size={14} className="text-[#4F626F] group-hover:text-[#D78A4A] shrink-0 transition" /><span className="font-display text-[10px] font-bold tracking-[.12em] text-[#80909C]">{order.id}</span></div><span className="text-[9px] font-bold uppercase tracking-[.1em] flex items-center gap-1" style={{ color }}><span className="h-1.5 w-1.5 rounded-full" style={{ backgroundColor: color }} />{p}</span></div><h3 className="font-display text-sm font-semibold text-[#E8EEF2] mt-3 leading-5">{order.title}</h3>{order.description && <p className="text-[11px] leading-4 text-[#80909C] mt-1.5 line-clamp-2">{order.description}</p>}{pending && <div className="mt-3 rounded-md bg-[#D7B45A]/10 border border-[#D7B45A]/20 px-2.5 py-2 text-[10px] text-[#D7B45A]">Təsdiq gözləyir · {pending.label}</div>}{order.rejectedReason && <div className="mt-3 rounded-md bg-[#D77464]/10 border border-[#D77464]/20 px-2.5 py-2 text-[10px] text-[#E58A7C]">İmtina səbəbi: {order.rejectedReason}</div>}<div className="mt-4 pt-3 border-t border-white/[.07] flex items-center justify-between text-[10px] text-[#687A86]"><span className="flex items-center gap-1.5"><Clock3 size={12} />{formatDate(order.createdAt)}</span><span className="flex items-center gap-1.5 text-[#A3B1BA]" title="Cari mərhələdə keçən vaxt"><span className="h-1.5 w-1.5 rounded-full bg-[#D78A4A]" />{durationLabel(order.stageEnteredAt, now)}</span></div></article> }
'''
s = s[:start] + replacement + s[end:]
old = '<label className="block"><span className="text-xs font-semibold text-[#B6C1C9]">Şəkil URL-i <span className="text-[#657783] font-normal">(opsional)</span></span><div className="relative mt-2"><ImagePlus size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#718391]" /><input value={form.image} onChange={(e) => setForm((f) => ({ ...f, image: e.target.value }))} placeholder="https://..." className="w-full rounded-lg border border-white/10 bg-[#07121B] pl-9 pr-3.5 py-3 text-sm outline-none focus:border-[#D78A4A] transition placeholder:text-[#536571]" /></div></label>'
new = '<label className="block"><span className="text-xs font-semibold text-[#B6C1C9]">Sifariş şəkli <span className="text-[#657783] font-normal">(opsional)</span></span><div className="relative mt-2"><input type="file" accept="image/*" onChange={(e) => { const file = e.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setForm((f) => ({ ...f, image: String(reader.result || "") })); reader.readAsDataURL(file); }} className="block w-full rounded-lg border border-white/10 bg-[#07121B] px-3 py-2.5 text-xs text-[#A8B6C0] file:mr-3 file:rounded-md file:border-0 file:bg-[#D78A4A] file:px-3 file:py-1.5 file:text-xs file:font-bold file:text-[#1B1713]" /></div></label>'
if old not in s: raise SystemExit('image input pattern missing')
s = s.replace(old, new)
p.write_text(s)
