import { and, desc, eq, or } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { prolineNotifications, prolineOrders, users, type InsertProlineOrder, type InsertUser } from "../drizzle/schema";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required"); const db = await getDb(); if (!db) return; await db.insert(users).values({ ...user, lastSignedIn: user.lastSignedIn || new Date() }).onDuplicateKeyUpdate({ set: { name: user.name, email: user.email, loginMethod: user.loginMethod, role: user.role, prolineRole: user.prolineRole, lastSignedIn: new Date() } }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function getOrCreateProlineUser(email: string, label: string, prolineRole: string) { const openId = `proline:${email}`; await upsertUser({ openId, name: label, email, loginMethod: "proline-code", role: prolineRole === "admin" ? "admin" : "user", prolineRole }); return getUserByOpenId(openId); }
export async function listBoardData(email: string) { const db = await getDb(); if (!db) return { orders: [], notifications: [], staff: [] }; const operator = await db.select().from(users).where(eq(users.email, email)).limit(1); await db.update(users).set({ lastSignedIn: new Date() }).where(eq(users.email, email)); const staffRows = await db.select({ email: users.email, name: users.name, prolineRole: users.prolineRole, lastSignedIn: users.lastSignedIn }).from(users); const staff = staffRows.map((member) => ({ email: member.email || "", label: member.name || member.email || "Operator", online: Date.now() - new Date(member.lastSignedIn).getTime() < 45000 })); const role = operator[0]?.prolineRole || "admin"; const notifications = role === "admin" ? await db.select().from(prolineNotifications).where(or(and(eq(prolineNotifications.requesterUserId, operator[0]?.id || -1), eq(prolineNotifications.status, "pending")), and(eq(prolineNotifications.targetRole, "admin"), eq(prolineNotifications.status, "pending")))).orderBy(desc(prolineNotifications.createdAt)) : await db.select().from(prolineNotifications).where(and(eq(prolineNotifications.targetRole, role), eq(prolineNotifications.status, "pending"))).orderBy(desc(prolineNotifications.createdAt)); const orders = await db.select().from(prolineOrders).orderBy(desc(prolineOrders.createdAt)); return { orders, notifications, staff }; }
export async function insertOrder(order: InsertProlineOrder) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.insert(prolineOrders).values(order); const rows = await db.select().from(prolineOrders).where(eq(prolineOrders.publicId, order.publicId)).limit(1); return rows[0]; }
