import { z } from "zod";
import { randomUUID } from "node:crypto";
import { eq } from "drizzle-orm";
import { SignJWT, jwtVerify } from "jose";
import { prolineNotifications, prolineOrders, users } from "../drizzle/schema";
import { addAuditLog, exportOrders, getAuditLogs, getDb, getNotificationPreference, getOrCreateProlineUser, listBoardData, insertOrder, setNotificationPreference } from "./db";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, router } from "./_core/trpc";

const roleMap: Record<string, { role: string; label: string; column?: string }> = { "dispatcher@proline": { role: "admin", label: "Dispatcher / Admin" }, "production@proline": { role: "production", label: "İstehsalat", column: "production" }, "polishing@proline": { role: "polishing", label: "Cilalama", column: "polishing" }, "paint@proline": { role: "paint", label: "Boyalama", column: "paint" }, "warehouse@proline": { role: "warehouse", label: "Anbar", column: "warehouse" } };
const secret = new TextEncoder().encode(process.env.JWT_SECRET || "proline-local-session-secret");
async function signSession(email: string) { return new SignJWT({ email }).setProtectedHeader({ alg: "HS256" }).setIssuedAt().setExpirationTime("12h").sign(secret); }
async function sessionEmail(req: { headers: { cookie?: string } }) { const raw = req.headers.cookie?.split(";").map((v) => v.trim()).find((v) => v.startsWith("proline_session="))?.split("=")[1]; if (!raw) throw new Error("PROLINE session tələb olunur"); try { const verified = await jwtVerify(raw, secret); return String(verified.payload.email); } catch { throw new Error("PROLINE session etibarsızdır"); } }

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query(opts => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); ctx.res.clearCookie("proline_session", { httpOnly: true, sameSite: "lax", secure: true, path: "/", maxAge: 0 }); return { success: true } as const; }) }),
  board: router({
    session: publicProcedure.query(async ({ ctx }) => { const email = await sessionEmail(ctx.req); const found = roleMap[email]; if (!found) throw new Error("PROLINE session etibarsızdır"); const db = await getDb(); const rows = db ? await db.select().from(users).where(eq(users.email, email)).limit(1) : []; return { email, role: found.role, label: found.label, column: found.column, userId: rows[0]?.id || 0 }; }),
    login: publicProcedure.input(z.object({ email: z.string(), code: z.string() })).mutation(async ({ input, ctx }) => { const normalized = input.email.trim().toLowerCase(); const found = roleMap[normalized]; if (!found || input.code !== "010203") throw new Error("Email və ya giriş kodu yanlışdır."); const saved = await getOrCreateProlineUser(normalized, found.label, found.role); const token = await signSession(normalized); ctx.res.cookie("proline_session", token, { httpOnly: true, sameSite: "lax", secure: true, path: "/", maxAge: 12 * 60 * 60 * 1000 }); return { email: normalized, role: found.role, label: found.label, column: found.column, userId: saved?.id || 0 }; }),
    list: publicProcedure.query(async ({ ctx }) => listBoardData(await sessionEmail(ctx.req))),
    heartbeat: publicProcedure.mutation(async ({ ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const email = await sessionEmail(ctx.req); await db.update(users).set({ lastSignedIn: new Date() }).where(eq(users.email, email)); return { success: true }; }),
    notificationPreference: publicProcedure.query(async ({ ctx }) => getNotificationPreference(await sessionEmail(ctx.req))),
    setNotificationPreference: publicProcedure.input(z.object({ enabled: z.boolean() })).mutation(async ({ input, ctx }) => setNotificationPreference(await sessionEmail(ctx.req), input.enabled)),
    audit: publicProcedure.input(z.object({ orderId: z.number().optional() }).optional()).query(async ({ input, ctx }) => { await sessionEmail(ctx.req); return getAuditLogs(input?.orderId); }),
    export: publicProcedure.query(async ({ ctx }) => { await sessionEmail(ctx.req); return exportOrders(); }),
    create: publicProcedure.input(z.object({ title: z.string().min(1), description: z.string().optional(), imageUrl: z.string().optional(), priority: z.enum(["low", "normal", "high", "urgent"]) })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const email = await sessionEmail(ctx.req); const operatorRows = await db.select().from(users).where(eq(users.email, email)).limit(1); const operator = operatorRows[0]; if (!operator || operator.prolineRole !== "admin") throw new Error("Yalnız Dispatcher sifariş yarada bilər."); const created = await insertOrder({ publicId: `PL-${randomUUID().replaceAll("-", "").slice(0, 28)}`, title: input.title, description: input.description || null, imageUrl: input.imageUrl || null, priority: input.priority, columnId: "orders", createdByUserId: operator.id, stageEnteredAt: new Date() }); if (created) await addAuditLog({ orderId: created.id, actorUserId: operator.id, action: "created", toColumn: "orders", details: "Sifariş yaradıldı" }); return created; }),
    update: publicProcedure.input(z.object({ orderId: z.number(), title: z.string().min(1), description: z.string().optional(), imageUrl: z.string().optional(), priority: z.enum(["low", "normal", "high", "urgent"]) })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const email = await sessionEmail(ctx.req); const operatorRows = await db.select().from(users).where(eq(users.email, email)).limit(1); if (operatorRows[0]?.prolineRole !== "admin") throw new Error("Yalnız Dispatcher redaktə edə bilər."); await db.update(prolineOrders).set({ title: input.title, description: input.description || null, imageUrl: input.imageUrl || null, priority: input.priority }).where(eq(prolineOrders.id, input.orderId)); if (operatorRows[0]) await addAuditLog({ orderId: input.orderId, actorUserId: operatorRows[0].id, action: "updated", details: "Sifariş redaktə edildi" }); return { success: true }; }),
    requestMove: publicProcedure.input(z.object({ orderId: z.number(), toColumn: z.enum(["orders", "production", "polishing", "paint", "warehouse"]) })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const email = await sessionEmail(ctx.req); const operator = await db.select().from(users).where(eq(users.email, email)).limit(1); const current = operator[0]; if (!current) throw new Error("Operator tapılmadı"); const rows = await db.select().from(prolineOrders).where(eq(prolineOrders.id, input.orderId)).limit(1); const order = rows[0]; if (!order) throw new Error("Sifariş tapılmadı"); if (current.prolineRole !== "admin" && current.prolineRole !== order.columnId) throw new Error("Bu sütundan sifariş göndərmək icazəniz yoxdur."); const targetRole = input.toColumn === "orders" ? "admin" : input.toColumn; await db.update(prolineOrders).set({ pendingTo: input.toColumn, rejectedReason: null }).where(eq(prolineOrders.id, input.orderId)); await db.insert(prolineNotifications).values({ orderId: input.orderId, fromColumn: order.columnId, toColumn: input.toColumn, requesterUserId: current.id, targetRole, status: "pending" }); await addAuditLog({ orderId: input.orderId, actorUserId: current.id, action: "move_requested", fromColumn: order.columnId, toColumn: input.toColumn, details: "Mərhələ keçidi üçün təsdiq göndərildi" }); return { success: true }; }),
    respond: publicProcedure.input(z.object({ notificationId: z.number(), accepted: z.boolean(), reason: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const email = await sessionEmail(ctx.req); const operatorRows = await db.select().from(users).where(eq(users.email, email)).limit(1); const operator = operatorRows[0]; const notices = await db.select().from(prolineNotifications).where(eq(prolineNotifications.id, input.notificationId)).limit(1); const notice = notices[0]; if (!notice) throw new Error("Bildiriş tapılmadı"); if (!operator || operator.prolineRole !== notice.targetRole) throw new Error("Bu bildirişə cavab vermək icazəniz yoxdur."); await db.update(prolineNotifications).set({ status: input.accepted ? "accepted" : "rejected", reason: input.reason || null, respondedAt: new Date() }).where(eq(prolineNotifications.id, input.notificationId)); if (input.accepted) { await db.update(prolineOrders).set({ columnId: notice.toColumn, pendingTo: null, rejectedReason: null, stageEnteredAt: new Date() }).where(eq(prolineOrders.id, notice.orderId)); await addAuditLog({ orderId: notice.orderId, actorUserId: operator.id, action: "accepted", fromColumn: notice.fromColumn, toColumn: notice.toColumn, details: "Mərhələ keçidi qəbul edildi" }); } else { await db.update(prolineOrders).set({ pendingTo: null, rejectedReason: input.reason || "Səbəb qeyd edilməyib." }).where(eq(prolineOrders.id, notice.orderId)); await addAuditLog({ orderId: notice.orderId, actorUserId: operator.id, action: "rejected", fromColumn: notice.fromColumn, toColumn: notice.toColumn, details: input.reason || "Mərhələ keçidi rədd edildi" }); } return { success: true }; }),
  }),
});
export type AppRouter = typeof appRouter;
